### ISSUE TITLE
I met a problem when running the command python -m streamlit run main.py

### ISSUE THREAD

**Issue by Levin-l1ang** [chenwr727/Smart-Album#9]
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.3.24:8501

2024-10-23 15:32:12.244 Uncaught app exception
Traceback (most recent call last):
  File "D:\ChatTTS\.venv\FaceAlbumMind\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "D:\ChatTTS\.venv\FaceAlbumMind\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\Lucosm1\Desktop\FaceAlbumMind\main.py", line 6, in <module>
    from insightface.app import FaceAnalysis
  File "D:\ChatTTS\.venv\FaceAlbumMind\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "D:\ChatTTS\.venv\FaceAlbumMind\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "D:\ChatTTS\.venv\FaceAlbumMind\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "D:\ChatTTS\.venv\FaceAlbumMind\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "D:\ChatTTS\.venv\FaceAlbumMind\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。

**Comment by Levin-l1ang** [comment]
sry but I have fixed it lol
